import React, { useState } from 'react';
import { CheckCircle2, Mail, MapPin, Phone, Send } from 'lucide-react';

export default function Contact({ isModal, onClose }) {
  const [formData, setFormData] = useState({ name: '', email: '', phone: '', service: 'Photovoltaic systems', message: '' });
  const [submitted, setSubmitted] = useState(false);
  const update = (key, value) => setFormData({ ...formData, [key]: value });
  const handleSubmit = (e) => { e.preventDefault(); setSubmitted(true); };
  const formContent = submitted ? <div className="text-center py-8 space-y-3"><div className="w-12 h-12 bg-emerald-100 text-emerald-700 rounded-full flex items-center justify-center mx-auto"><CheckCircle2 className="w-7 h-7" /></div><h3 className="text-xl font-bold text-slate-950">Thank you, {formData.name || 'there'}.</h3><p className="text-slate-600 text-sm max-w-sm mx-auto">Your inquiry has been noted. The Mashariki Energy team will review your requirements and respond with the appropriate next step.</p>{onClose && <button onClick={onClose} className="bg-emerald-700 text-white font-bold px-5 py-2 rounded-lg text-sm">Close</button>}</div> : <form onSubmit={handleSubmit} className="space-y-4"><div className="grid sm:grid-cols-2 gap-4"><label className="field"><span>Name *</span><input required value={formData.name} onChange={(e) => update('name', e.target.value)} placeholder="Your name" /></label><label className="field"><span>Email *</span><input required type="email" value={formData.email} onChange={(e) => update('email', e.target.value)} placeholder="you@company.com" /></label></div><div className="grid sm:grid-cols-2 gap-4"><label className="field"><span>Phone</span><input type="tel" value={formData.phone} onChange={(e) => update('phone', e.target.value)} placeholder="Phone number" /></label><label className="field"><span>Area of interest</span><select value={formData.service} onChange={(e) => update('service', e.target.value)}><option>Photovoltaic systems</option><option>Energy storage</option><option>EV charging stations</option><option>Clean cooking equipment</option><option>Smart kitchens</option></select></label></div><label className="field"><span>Project details</span><textarea rows="4" value={formData.message} onChange={(e) => update('message', e.target.value)} placeholder="Tell us about your site, institution, or energy requirement..." /></label><button type="submit" className="w-full flex items-center justify-center gap-2 bg-emerald-700 hover:bg-emerald-800 text-white font-bold py-3 rounded-xl transition-colors"><Send className="w-4 h-4" /> Send inquiry</button></form>;
  if (isModal) return formContent;
  return <section id="contact" className="py-20 lg:py-28 bg-[#eef1eb]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-2xl mb-12"><p className="eyebrow">Contact</p><h2 className="section-title">Let’s discuss what your site needs.</h2><p className="mt-5 text-slate-600 leading-relaxed">Tell us what you are planning, improving, or trying to solve. We will help you identify the right starting point.</p></div><div className="grid lg:grid-cols-12 gap-8"><div className="lg:col-span-4 bg-[#173f2b] text-white p-7 rounded-2xl"><h3 className="font-semibold text-xl">Mashariki Energy Ltd</h3><div className="mt-8 space-y-5 text-sm"><div className="flex gap-3"><MapPin className="w-5 h-5 text-[#c9e86b] shrink-0" /><span>Centenary House KN 72, 5th Floor<br />Kigali, Rwanda</span></div><div className="flex gap-3"><Phone className="w-5 h-5 text-[#c9e86b] shrink-0" /><span>0788308619<br />0788595334</span></div><div className="flex gap-3"><Mail className="w-5 h-5 text-[#c9e86b] shrink-0" /><span>info@mashariki-energy.com</span></div></div></div><div className="lg:col-span-8 bg-white p-7 rounded-2xl border border-slate-200"><h3 className="text-xl font-semibold text-slate-950 mb-5">Send an inquiry</h3>{formContent}</div></div></div></section>;
}
