import React from 'react';
import { Mail, MapPin, Phone, Sun } from 'lucide-react';

const quickLinks = [['Home', 'home'], ['About Us', 'about'], ['Services', 'services'], ['Why Us', 'why-us'], ['Contact', 'contact']];
const services = ['Photovoltaic systems', 'Energy storage', 'EV charging stations', 'Clean cooking equipment', 'Smart kitchens'];

export default function Footer() {
  const scrollTo = (id) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  return <footer className="bg-[#102c1f] text-white/70"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-14"><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-10"><div className="lg:col-span-1"><button onClick={() => scrollTo('home')} className="flex items-center gap-3 text-left"><span className="w-11 h-11 rounded-xl bg-[#c9e86b] text-[#173f2b] flex items-center justify-center"><Sun className="w-6 h-6" /></span><span><strong className="block text-lg text-white leading-none">Mashariki</strong><small className="block mt-1 text-[10px] tracking-[0.2em] text-[#c9e86b]">ENERGY LTD</small></span></button><p className="mt-5 text-sm leading-relaxed">Reliable energy systems for a more resilient future across Rwanda and beyond.</p></div><div><h3 className="text-sm font-bold uppercase tracking-[0.16em] text-white">Quick Links</h3><nav className="mt-5 space-y-3">{quickLinks.map(([label, id]) => <button key={id} onClick={() => scrollTo(id)} className="block text-sm hover:text-[#c9e86b] transition-colors">{label}</button>)}</nav></div><div><h3 className="text-sm font-bold uppercase tracking-[0.16em] text-white">Our Services</h3><ul className="mt-5 space-y-3">{services.map((service) => <li key={service} className="text-sm">{service}</li>)}</ul></div><div><h3 className="text-sm font-bold uppercase tracking-[0.16em] text-white">Contact Us</h3><div className="mt-5 space-y-4 text-sm"><a href="tel:0788308619" className="flex gap-3 hover:text-[#c9e86b] transition-colors"><Phone className="w-4 h-4 text-[#c9e86b] shrink-0" />0788308619 / 0788595334</a><a href="mailto:info@mashariki-energy.com" className="flex gap-3 hover:text-[#c9e86b] transition-colors"><Mail className="w-4 h-4 text-[#c9e86b] shrink-0" />info@mashariki-energy.com</a><span className="flex gap-3"><MapPin className="w-4 h-4 text-[#c9e86b] shrink-0" />Centenary House KN 72, 5th Floor<br />Kigali, Rwanda</span></div></div></div></div><div className="border-t border-white/10"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-5 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs"><span>© {new Date().getFullYear()} Mashariki Energy Ltd. All rights reserved.</span><span>Designed with ❤️ by <a href="https://1000-hills.netlify.app/" target="_blank" rel="noopener noreferrer" className="text-[#c9e86b] hover:text-white transition-colors">1000 Hills Group</a></span></div></div></footer>;
}
