import React, { useState } from 'react';
import { Menu, Sun, X } from 'lucide-react';

export default function Navbar({ activeSection, setActiveSection, onOpenQuote }) {
  const [open, setOpen] = useState(false);
  const links = [['About', 'about'], ['Services', 'services'], ['Why us', 'why-us'], ['Contact', 'contact']];
  const go = (id) => { setActiveSection(id); setOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); };
  return <header className="fixed top-0 left-0 right-0 z-40 bg-[#173f2b]/95 backdrop-blur-md text-white border-b border-white/10"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-[104px] flex items-center justify-between"><button onClick={() => go('home')} className="flex items-center gap-3 text-left"><span className="w-10 h-10 rounded-xl bg-[#c9e86b] text-[#173f2b] flex items-center justify-center"><Sun className="w-6 h-6" /></span><span><strong className="block text-lg leading-none">Mashariki</strong><small className="block mt-1 text-[10px] tracking-[0.2em] text-[#c9e86b]">ENERGY LTD</small></span></button><nav className="hidden md:flex items-center gap-1">{links.map(([label, id]) => <button key={id} onClick={() => go(id)} className={`px-4 py-2 rounded-full text-sm transition-colors ${activeSection === id ? 'bg-white/10 text-[#c9e86b]' : 'text-white/70 hover:text-white'}`}>{label}</button>)}</nav><button onClick={onOpenQuote} className="hidden md:inline-flex bg-[#c9e86b] hover:bg-[#d8f28e] text-[#173f2b] font-bold text-sm px-5 py-2.5 rounded-full transition-colors">Start a conversation</button><button className="md:hidden p-2" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X /> : <Menu />}</button></div>{open && <nav className="md:hidden px-4 pb-5 space-y-1 border-t border-white/10">{links.map(([label, id]) => <button key={id} onClick={() => go(id)} className="block w-full text-left px-3 py-3 text-white/80">{label}</button>)}<button onClick={onOpenQuote} className="w-full mt-2 bg-[#c9e86b] text-[#173f2b] font-bold py-3 rounded-xl">Start a conversation</button></nav>}</header>;
}
